---
name: Ross
surname: Kwok
position: "Geneticist"
address: "Edinburgh, Scotland"
github: RTKwok
orcid: 0000-0002-2569-3881
email: "ross.kwok@research.staffs.ac.uk"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
aboutme: "I am a geneticist specilised in population genetics and genomic laboratory practices. I have recently completed my PhD studies in Forensic Science at Staffordshire University and I am due to graduate in July 2023. My research investigated the feasibility of acquiring DNA profiles from counterfeit currency. My previous and current degrees have provided me with significant experience in using equipment specific to DNA analysis including thermal cyclers and genetic analysers alongside various techniques in DNA extraction and genetic sample evaluation."
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
require(xfun)
packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )
xfun::pkg_attach2(packages, message = FALSE)
source(file = "C:\\Users\\user\\OneDrive - Staffordshire University\\Job CV 2022\\Ross_K_CV\\Data\\rossCV_data.r")
```

# Education

```{r EDUCATION}
edu %>%
  detailed_entries(
    with = degree,
    what = inst,
    why = title,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
  )
```

# Employment

```{r EMPLOYMENT}
work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )
```

# Skillset

```{r SKILLS}
skills %>%
  detailed_entries(
    with = area,
    what = skills
  )
```

# Conferences

```{r HONORS}
conf %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    when = year,
    where = where
  )
```

# Publications

```{r WORKS}
works %>% #~author, ~title, ~year, ~where, ~doi,
  detailed_entries(
    with = author,
    when = year,
    what = title,
    why = doi,
    where = where
  )
```

# Memberships

```{r PARTICIPATION}
memb %>% #~group, ~title, ~about, ~where,
  detailed_entries(
    with = group
  )
```

